services:
  app:
    build: .
    container_name: ds-assgn-1
    command: uvicorn broker.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - ds_assgn_1_volume:/code
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ds_assgn_1_volume:/var/lib/postgresSQL/data
    ports:
      - 5432:5432
  
  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050

volumes:
  ds_assgn_1_volume: {}