services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ds-assgn-1
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
#      - ./broker/database.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - 5433:5432

  app:
    build: ./broker
    container_name: distributed-queue-broker
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=ds-assgn-1
    ports:
      - 8080:80
      - 5678:5678
    volumes:
      - ./broker:/code
    depends_on:
      - postgres

  
