services:
  raft-broker1:
    build: ./raft-broker
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - BROKER=distributed-queue-raft-broker1-1
      - LEADER_URL=http://host.docker.internal:8091
    ports:
      - 8000:8000
    volumes:
      - ./raft-broker:/code
    networks:
      - raft-net
  
  raft-broker2:
    build: ./raft-broker
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - BROKER=distributed-queue-raft-broker2-1
      - LEADER_URL=http://host.docker.internal:8091
    ports:
      - 8001:8000
    volumes:
      - ./raft-broker:/code
    networks:
      - raft-net
  
  raft-broker3:
    build: ./raft-broker
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - BROKER=distributed-queue-raft-broker3
      - LEADER_URL=http://host.docker.internal:8091
    ports:
      - 8002:8000
    volumes:
      - ./raft-broker:/code
    networks:
      - raft-net
  
networks:
  raft-net:
    driver: bridge
