services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ds-assgn-1
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    #      - ./broker/database.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - 5432
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ds-assgn-1" ]
      interval: 15s
      timeout: 30s
      retries: 5
      start_period: 5s

  app:
    build: ./broker
    container_name: distributed-queue-broker
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_NAME=ds-assgn-1
    ports:
      - 8080:80
      - 5678:5678
    volumes:
      - ./broker:/code
    depends_on:
      postgres:
        condition: service_healthy

# Redis
  redis:
    image: redislabs/rejson:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    command: redis-server 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Broker Manager
  broker-manager:
    build: ./broker-manager
    container_name: broker-manager
    command: uvicorn main:app --host 0.0.0.0 --port 81 --reload
    ports:
      - 8081:81
    volumes:
      - ./broker-manager:/code
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
